### ISSUE TITLE
Wrong behavior on Example Number 2 at the demo page

### ISSUE THREAD

**Issue by margsot** [vicb/bsmSelect#41]
Hi, on the demo page at the example2 if you add a city in the input field and click the add button it works ok but also submit empty values which is wrong how can we fix this ???

Thanks

**Comment by vicb** [comment]
Can not reproduce, what browser are you testing with ?

**Comment by margsot** [comment]
I tested it with Firefox and Chrome. The same Behavior. Go to example 2 and at the field "add a city?" don't type anything and click the add button.  it will create new empty options !!

**Comment by vicb** [comment]
Oh sorry, didn't get that by reading your initial issue report.

Adding `if (city.trim() === '') return false;` on line [74](https://github.com/vicb/bsmSelect/blob/master/examples/index.html#L73) should fix this.
